### ISSUE TITLE
I get an error with EpollSelector.

### ISSUE THREAD

**Issue by ninjasaid2k** [Fantasy-Studio/Paint-by-Example#2]
```
(Paint-by-Example) C:\Users\username\Paint-by-Example-main>sh test.sh
Global seed set to 321
Loading model from checkpoints/model.ckpt
Global Step: 32613
Traceback (most recent call last):
  File "scripts/inference.py", line 444, in <module>
    main()
  File "scripts/inference.py", line 300, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/inference.py", line 65, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "c:\users\username\paint-by-example-main\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\users\username\paint-by-example-main\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\Users\username\anaconda3\envs\Paint-by-Example\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\username\paint-by-example-main\ldm\models\diffusion\ddpm.py", line 9, in <module>
    from selectors import EpollSelector
ImportError: cannot import name 'EpollSelector' from 'selectors' (C:\Users\username\anaconda3\envs\Paint-by-Example\lib\selectors.py)

```
I'm using Windows 10.

**Comment by Fantasy-Studio** [comment]
EpollSelector and Windows are incompatible, can you try linux?
