### ISSUE TITLE
Question about LDM.

### ISSUE THREAD

**Issue by chenhaoxing** [Fantasy-Studio/Paint-by-Example#6]
Traceback (most recent call last):
  File "inference.py", line 405, in <module>
    main()
  File "inference.py", line 271, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "inference.py", line 63, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/yansan/projects/PaintExam/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/yansan/projects/PaintExam/ldm/models/diffusion/ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'u_cond_percent'

**Comment by Gal4way** [comment]
do you know how to solve this problem now?

**Comment by cfanyyx** [comment]
do you know how to solve this problem now?

**Comment by KleinXin** [comment]
Same error. Maybe it is the problem of the version of the diffuser

**Comment by loliq** [comment]
hello, did you solve this problem, I met the same error.
